-- ============================================================
--  PAZ CHURCH PARAIPABA -- SUPABASE COMPLETO
--  Execute inteiro no SQL Editor do seu novo projeto:
--  https://csxitgraaawziaflveol.supabase.co
-- ============================================================


-- ══════════════════════════════════════════
-- 1. MEMBROS (cadastro principal do bot)
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS members_paraipaba (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone           TEXT NOT NULL UNIQUE,
    name            TEXT,
    email           TEXT,
    address         TEXT,
    neighborhood    TEXT,
    birthday        DATE,
    life_group      TEXT,          -- nome da Life Group / célula
    member_since    DATE DEFAULT CURRENT_DATE,
    is_active       BOOLEAN DEFAULT TRUE,
    notes           TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_members_phone ON members_paraipaba(phone);
CREATE INDEX IF NOT EXISTS idx_members_birthday ON members_paraipaba(birthday);
CREATE INDEX IF NOT EXISTS idx_members_life_group ON members_paraipaba(life_group);


-- ══════════════════════════════════════════
-- 2. LIFE GROUPS / CÉLULAS (Paraipaba)
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS lives_paraipaba (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    leader      TEXT,
    address     TEXT,
    day_of_week TEXT,              -- ex: 'Terça-feira'
    time        TEXT,              -- ex: '19h30'
    neighborhood TEXT,
    phone       TEXT,             -- WhatsApp do líder
    active      BOOLEAN DEFAULT TRUE,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);


-- ══════════════════════════════════════════
-- 3. LIFE GROUPS / CÉLULAS (Mondubim)
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS lives_mondubim (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        TEXT NOT NULL,
    leader      TEXT,
    address     TEXT,
    day_of_week TEXT,
    time        TEXT,
    neighborhood TEXT,
    phone       TEXT,
    active      BOOLEAN DEFAULT TRUE,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);


-- ══════════════════════════════════════════
-- 4. CHECK-IN (presença nos cultos)
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS checkin_log (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone         TEXT NOT NULL,
    member_name   TEXT,
    checked_in_at TIMESTAMPTZ DEFAULT NOW(),
    event_name    TEXT DEFAULT 'Culto Dominical',
    day_of_week   INT,             -- 0=Dom … 6=Sáb
    notes         TEXT
);

CREATE INDEX IF NOT EXISTS idx_checkin_phone   ON checkin_log(phone);
CREATE INDEX IF NOT EXISTS idx_checkin_date    ON checkin_log(checked_in_at DESC);


-- ══════════════════════════════════════════
-- 5. PEDIDOS DE ORAÇÃO
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS prayer_requests (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone       TEXT NOT NULL,
    member_name TEXT,
    request     TEXT NOT NULL,
    answered    BOOLEAN DEFAULT FALSE,
    created_at  TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_prayer_created ON prayer_requests(created_at DESC);


-- ══════════════════════════════════════════
-- 6. CADASTRO DE CASAMENTOS / EVENTOS
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS wedding_registrations (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone           TEXT NOT NULL,
    groom_name      TEXT,
    bride_name      TEXT,
    wedding_date    DATE,
    ceremony_time   TEXT,
    reception_venue TEXT,
    guest_count     INT,
    notes           TEXT,
    created_at      TIMESTAMPTZ DEFAULT NOW()
);


-- ══════════════════════════════════════════
-- 7. LOG DE DISPAROS PROATIVOS (scheduler)
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS proactive_outreach_log (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone       TEXT NOT NULL,
    type        TEXT,              -- 'birthday', 'follow_up', etc.
    sent_at     TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(phone, type, sent_at)   -- evita duplicatas no mesmo dia
);

CREATE INDEX IF NOT EXISTS idx_outreach_phone ON proactive_outreach_log(phone);
CREATE INDEX IF NOT EXISTS idx_outreach_type  ON proactive_outreach_log(type, sent_at DESC);


-- ══════════════════════════════════════════
-- 8. PAZ KIDS – CHECK-IN INFANTIL ← NOVO
-- ══════════════════════════════════════════
CREATE TABLE IF NOT EXISTS children (
    id           UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    number       INT NOT NULL,              -- número de chamada no culto
    child_name   TEXT,
    parent_name  TEXT,
    parent_phone TEXT,                      -- WhatsApp do responsável
    age_group    TEXT CHECK (age_group IN ('bebe','maternal','jardim','primario','junior')),
    status       TEXT DEFAULT 'green' CHECK (status IN ('green','red')),
    checkin_at   TIMESTAMPTZ DEFAULT NOW(),
    checkout_at  TIMESTAMPTZ,               -- preenchido ao liberar saída
    notes        TEXT
);

CREATE INDEX IF NOT EXISTS idx_children_number ON children(number);
CREATE INDEX IF NOT EXISTS idx_children_status ON children(status);
CREATE INDEX IF NOT EXISTS idx_children_date   ON children(checkin_at DESC);

-- Habilitar Realtime para o Paz Kids (necessário para atualizações ao vivo)
ALTER PUBLICATION supabase_realtime ADD TABLE children;


-- ══════════════════════════════════════════
-- 9. ROW LEVEL SECURITY (RLS)
-- Deixar DESABILITADO nas tabelas que o bot
-- acessa com a anon key (mais simples).
-- ══════════════════════════════════════════
ALTER TABLE members_paraipaba       DISABLE ROW LEVEL SECURITY;
ALTER TABLE lives_paraipaba         DISABLE ROW LEVEL SECURITY;
ALTER TABLE lives_mondubim          DISABLE ROW LEVEL SECURITY;
ALTER TABLE checkin_log             DISABLE ROW LEVEL SECURITY;
ALTER TABLE prayer_requests         DISABLE ROW LEVEL SECURITY;
ALTER TABLE wedding_registrations   DISABLE ROW LEVEL SECURITY;
ALTER TABLE proactive_outreach_log  DISABLE ROW LEVEL SECURITY;
ALTER TABLE children                DISABLE ROW LEVEL SECURITY;


-- ══════════════════════════════════════════
-- 10. DADOS INICIAIS (opcional)
-- Insira suas Life Groups já cadastradas
-- ══════════════════════════════════════════

-- Exemplo de Life Group em Paraipaba:
-- INSERT INTO lives_paraipaba (name, leader, address, day_of_week, time, neighborhood)
-- VALUES ('Life Paraipaba Centro', 'Pr. Márcio', 'Rua Principal, 100', 'Quarta-feira', '19h30', 'Centro');

-- Exemplo de Life Group em Mondubim:
-- INSERT INTO lives_mondubim (name, leader, address, day_of_week, time, neighborhood)
-- VALUES ('Life Mondubim Norte', 'Líder João', 'Rua das Flores, 200', 'Terça-feira', '20h00', 'Mondubim');
