-- Tabela de Inscrições para o Casamento Coletivo
CREATE TABLE IF NOT EXISTS wedding_registrations (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    couple_names  TEXT NOT NULL,
    phone_contact TEXT NOT NULL,
    civil_status  TEXT NOT NULL,
    requester_jid TEXT NOT NULL, -- JID do WhatsApp de quem iniciou o cadastro
    created_at    TIMESTAMPTZ DEFAULT NOW()
);

-- Permissões
ALTER TABLE wedding_registrations DISABLE ROW LEVEL SECURITY;
